version: '3.8'

services:
  web:
    build: .
    ports:
      - "4050:4050"
    env_file: .docker.env
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: wf-public-profiles
      POSTGRES_PASSWORD: iamaninsecurepassword
      PG_TRUST_LOCALNET: true
    ports:
      - "5434:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db: