"""Initial create

Revision ID: 5dc3336a2045
Revises: 
Create Date: 2023-03-24 11:12:47.851220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dc3336a2045'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publicprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('holaspirit_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publicprofile_holaspirit_id'), 'publicprofile', ['holaspirit_id'], unique=False)
    op.create_index(op.f('ix_publicprofile_id'), 'publicprofile', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publicprofile_id'), table_name='publicprofile')
    op.drop_index(op.f('ix_publicprofile_holaspirit_id'), table_name='publicprofile')
    op.drop_table('publicprofile')
    # ### end Alembic commands ###
